services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  client_handler:
    container_name: client_handler
    environment:
      - ID=client_handler
      - MERGER_INSTANCES=3
      - DATA_DROPPER_INSTANCES=1
      - WEATHER_JOINER_INSTANCES=1
      - STATIONS_JOINER_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: client_handler:latest
    entrypoint: /client_handler
    restart: on-failure
    depends_on:
      - data_dropper_0

    volumes:
      - type: bind
        source: ./client_handler/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/client_handler:/recovery_files/

  
  client_0:
    container_name: client_0
    image: client:latest
    entrypoint: /client
    restart: on-failure
    depends_on:
      - client_handler
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./data/recovery_data/client_0:/recovery_files/

  client_1:
    container_name: client_1
    image: client:latest
    entrypoint: /client
    restart: on-failure
    depends_on:
      - client_handler
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./data/recovery_data/client_1:/recovery_files/

  client_2:
    container_name: client_2
    image: client:latest
    entrypoint: /client
    restart: on-failure
    depends_on:
      - client_handler
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./data/recovery_data/client_2:/recovery_files/

  client_3:
    container_name: client_3
    image: client:latest
    entrypoint: /client
    restart: on-failure
    depends_on:
      - client_handler
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./data/recovery_data/client_3:/recovery_files/

  client_4:
    container_name: client_4
    image: client:latest
    entrypoint: /client
    restart: on-failure
    depends_on:
      - client_handler
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - ./data/recovery_data/client_4:/recovery_files/


  duration_merger:
    container_name: duration_merger
    environment:
      - ID=duration_merger
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: duration_merger:latest
    entrypoint: /duration_merger
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./duration_merger/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/duration_merger:/recovery_files/
  
  count_merger:
    container_name: count_merger
    environment:
      - ID=count_merger
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - YEAR_1=2016
      - YEAR_2=2017
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: count_merger:latest
    entrypoint: /count_merger
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./count_merger/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/count_merger:/recovery_files/

  distance_merger:
    container_name: distance_merger
    environment:
      - ID=distance_merger
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - MIN_DISTANCE=6
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: distance_merger:latest
    entrypoint: /distance_merger
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./distance_merger/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/distance_merger:/recovery_files/


  duration_averager_0:
    container_name: duration_averager_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: duration_averager:latest
    entrypoint: /duration_averager
    restart: on-failure
    depends_on:
      - duration_merger
    volumes:
      - type: bind
        source: ./duration_averager/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/duration_averager_0:/recovery_files/
        

  precipitation_filter_0:
    container_name: precipitation_filter_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - MIN_PRECIPITATIONS=30
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: precipitation_filter:latest
    entrypoint: /precipitation_filter
    restart: on-failure
    depends_on:
      - duration_averager_0

    volumes:
      - type: bind
        source: ./precipitation_filter/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/precipitation_filter_0:/recovery_files/
   

  weather_joiner_0:
    container_name: weather_joiner_0
    environment:
      - ID=0
      - CLIENT_HANDLER_INSTANCES=1
      - DATA_DROPPER_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: weather_joiner:latest
    entrypoint: /weather_joiner
    restart: on-failure
    depends_on:
      - precipitation_filter_0

    volumes:
      - type: bind
        source: ./weather_joiner/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/weather_joiner_0:/recovery_files/
   

  data_dropper_0:
    container_name: data_dropper_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=1
      - WEATHER_JOINER_INSTANCES=1
      - STATIONS_JOINER_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: data_dropper:latest
    entrypoint: /data_dropper
    restart: on-failure
    depends_on:
      - weather_joiner_0

      - stations_joiner_0

    volumes:
      - type: bind
        source: ./data_dropper/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/data_dropper_0:/recovery_files/
 

  stations_joiner_0:
    container_name: stations_joiner_0
    environment:
      - ID=0
      - CLIENT_HANDLER_INSTANCES=1
      - DATA_DROPPER_INSTANCES=1
      - YEAR_FILTER_INSTANCES=1
      - DISTANCE_CALCULATOR_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: stations_joiner:latest
    entrypoint: /stations_joiner
    restart: on-failure
    depends_on:
      - year_filter_0

      - distance_calculator_0

    volumes:
      - type: bind
        source: ./stations_joiner/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/stations_joiner_0:/recovery_files/


  year_filter_0:
    container_name: year_filter_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - YEAR_1=2016
      - YEAR_2=2017
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: year_filter:latest
    entrypoint: /year_filter
    restart: on-failure
    depends_on:
      - trip_counter_0

    volumes:
      - type: bind
        source: ./year_filter/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/year_filter_0:/recovery_files/


  trip_counter_0:
    container_name: trip_counter_0
    environment:
      - ID=0
      - YEAR_1=2016
      - YEAR_2=2017
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: trip_counter:latest
    entrypoint: /trip_counter
    restart: on-failure
    depends_on:
      - count_merger
    volumes:
      - type: bind
        source: ./trip_counter/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/trip_counter_0:/recovery_files/


  distance_calculator_0:
    container_name: distance_calculator_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: distance_calculator:latest
    entrypoint: /distance_calculator
    restart: on-failure
    depends_on:
      - distance_averager_0

    volumes:
      - type: bind
        source: ./distance_calculator/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/distance_calculator_0:/recovery_files/


  distance_averager_0:
    container_name: distance_averager_0
    environment:
      - ID=0
      - PREV_STAGE_INSTANCES=1
      - NEXT_STAGE_INSTANCES=1
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
    image: distance_averager:latest
    entrypoint: /distance_averager
    restart: on-failure
    depends_on:
      - distance_merger
    volumes:
      - type: bind
        source: ./distance_averager/middleware_config.yaml
        target: /middleware_config.yaml
      - ./data/recovery_data/distance_averager_0:/recovery_files/


  health_checker_0:
    container_name: health_checker_0
    environment:
      - HOSTNAME=health_checker_0
      - PEERS=health_checker_0,health_checker_1
      - TARGETS=trip_counter_0,duration_averager_0,distance_averager_0,precipitation_filter_0,distance_calculator_0,year_filter_0,weather_joiner_0,stations_joiner_0,data_dropper_0,health_checker_0,health_checker_1,client_handler,duration_merger,count_merger,distance_merger
    image: health_checker:latest
    entrypoint: python3 /app/main.py
    restart: on-failure
    volumes:
        - ./health_checker/main.py:/app/main.py
        - ./health_checker/health_checker.py:/app/health_checker.py
        - ./health_checker/messaging_protocol.py:/app/messaging_protocol.py
        - ./health_checker/leader_election/:/app/leader_election/
        - ./health_checker/replier/replier.py:/app/replier.py
        - /var/run/docker.sock:/var/run/docker.sock

  health_checker_1:
    container_name: health_checker_1
    environment:
      - HOSTNAME=health_checker_1
      - PEERS=health_checker_0,health_checker_1
      - TARGETS=trip_counter_0,duration_averager_0,distance_averager_0,precipitation_filter_0,distance_calculator_0,year_filter_0,weather_joiner_0,stations_joiner_0,data_dropper_0,health_checker_0,health_checker_1,client_handler,duration_merger,count_merger,distance_merger
    image: health_checker:latest
    entrypoint: python3 /app/main.py
    restart: on-failure
    volumes:
        - ./health_checker/main.py:/app/main.py
        - ./health_checker/health_checker.py:/app/health_checker.py
        - ./health_checker/messaging_protocol.py:/app/messaging_protocol.py
        - ./health_checker/leader_election/:/app/leader_election/
        - ./health_checker/replier/replier.py:/app/replier.py
        - /var/run/docker.sock:/var/run/docker.sock

