consumer:
  exchange_name: duration_averager
  prev_stage_instances_env: PREV_STAGE_INSTANCES
  filter_duplicate_batches: true
  messages_to_store:
    - TE
    - T
producer:
  exchange_name: duration_merger
  next_stage_instances_env: NEXT_STAGE_INSTANCES
  route_by_id: false
