consumer:
  exchange_name: distance_calculator
  prev_stage_instances_env: PREV_STAGE_INSTANCES
  messages_to_store:
    - TE
producer:
  exchange_name: distance_averager
  next_stage_instances_env: NEXT_STAGE_INSTANCES
  route_by_id: true
