consumer:
  exchange_name: stations_joiner
  prev_stage_instances_env: DATA_DROPPER_INSTANCES
  messages_to_store:
    - TE
    - SE
    - S
year_filter_producer:
  exchange_name: year_filter
  next_stage_instances_env: YEAR_FILTER_INSTANCES
  route_by_id: true
distance_calculator_producer:
  exchange_name: distance_calculator
  next_stage_instances_env: DISTANCE_CALCULATOR_INSTANCES
  route_by_id: true